### ISSUE TITLE
Input editor preview and gyro calibration don't work as expected

### ISSUE THREAD

**Issue by KiritoDv** [Kenix3/libultraship#106]
The issue comes from a fix on the ControlDeck, when the InputEditor is open or any other view, the game stops reading data from the controllers, because of that the stick preview and the gyro calibration don't work, as a few other bugs related to this.

This patch should fix it, its tested on both pc and switch

[Input Fix Patch](https://github.com/Kenix3/libultraship/files/10504505/fix.patch)

Demo:

https://user-images.githubusercontent.com/36680385/214713247-4acfe7ac-9c5e-4fdf-a597-a35b410e3a2a.mp4

**Comment by dcvz** [comment]
Didn't use the patch, but this is fixed in both #113 and #109
