### ISSUE TITLE
Fullscreen doesn't save monitor

### ISSUE THREAD

**Issue by Spodi** [Kenix3/libultraship#297]
If I exited SoH while it was in fullscreen and at my second monitor, the next start is always in fullscreen at my primary monitor. after that toggling back to windowed makes the window jump back to my secondary monitor.

TLDR: Monitor saves fine for windowed mode. It doesn't in fullscreen.

SoH build with PR https://github.com/HarbourMasters/Shipwright/pull/2881

**Comment by briaguya0** [comment]
Did this work before? Looking at <https://github.com/Kenix3/libultraship/pull/288> nothing stands out as *removing* "save which monitor this was fullscreen on" functionality

If this didn't work before and this is just a feature request, we'll need to build out ways to
* Save which monitor it was on (probably need to figure out some kind of unique id of some sort)
* Handle that monitor no longer being connected
* Handle that monitor now being in a different location?
* Handle that monitor having changed resolution?

**Comment by Spodi** [comment]
Well the old behavior for me was, that the game opened on the monitor form where it was started (be it windowed or fullscreen). I guess according to mouse position? This isn't the case anymore and fullscreen always opens on my primary monitor. I thought that happened because of position saving.

**Comment by Malkierian** [comment]
More details on the problems: https://github.com/HarbourMasters/Shipwright/issues/3028
