### ISSUE TITLE
Bongo Bongo fist attack

### ISSUE THREAD

**Issue by daveleone** [Kenix3/libultraship#306]
SoH version: Spock Charlie 7.0.2

If you dodge bongo bongo's fist attack the hand doesnt come back and its just stay stuck in that state. 
i later did some testing and it seems like this occurs if no clip is enabled

https://github.com/Kenix3/libultraship/assets/63382327/f3883d26-2bda-46c6-9756-a5299f09a34e

**Comment by Malkierian** [comment]
Wrong github XD
