### ISSUE TITLE
Remove `PulseAudioPlayer`

### ISSUE THREAD

**Issue by briaguya0** [Kenix3/libultraship#311]
SDL provides a great abstraction layer for audio. https://github.com/Kenix3/libultraship/blob/main/src/audio/SDLAudioPlayer.cpp accomplishes in 44 lines what takes https://github.com/Kenix3/libultraship/blob/main/src/audio/PulseAudioPlayer.cpp 191.

SDL supports many different audio drivers https://wiki.libsdl.org/SDL2/FAQUsingSDL#linux_1 (including pulseaudio)

I propose we remove `PulseAudioPlayer` and rely on SDL audio for linux instead.

**Comment by Kenix3** [comment]
Seems good to me. I think marking it as deprecated in the next release, and removing it in the next major release makes sense here.
Will leave this open for comments before accepting the proposal until June 21st.

**Comment by vanfanel** [comment]
Builds and works well for me after removing pulseaudio manually.

**Comment by Kenix3** [comment]
Implemented in `next` branch for `2.0.0`
