### ISSUE TITLE
power save settings are lost after playing SOH on Windows

### ISSUE THREAD

**Issue by th-2021** [Kenix3/libultraship#336]
Power settings (e.g. Monitor standby) is lost after playing SOH on Windows. Version is latest (7.1.1).

**Comment by Spodi** [comment]
Define "is lost"? Can you reproduce that and show before playing and after playing? I think it should be impossible for SoH to change that.

**Comment by Kenix3** [comment]
This is an SoH bug report, not an LUS bug report. Also, we don't modify power settings.
