### ISSUE TITLE
Discovery: Controller mapping/configuration UX

### ISSUE THREAD

**Issue by briaguya0** [Kenix3/libultraship#342]
## Motivation/User Stories
* As a player of a ports using LUS, I should be able to map/configure my controller(s) intuitively.
* As a developer of a port using LUS, I should be able to provide a tailored controller mapping/configuration experience for players.
* As a developer of a port using LUS, I should be able to get up and running without building my own controller mapping/configuration menu.

## Definitions
* "I should be able to map/configure my controller(s) intuitively."
  * For the LUS provided menu, following best practices used by emulators makes sense. Mapping from button/axis on a physical device to N64 button/axis using language related to N64 buttons/axes provides all the functionality a port will need to get up and running. "Intuitive," in this case, means "intuitive to people familiar with the original game controls on N64 and familiar with controller mapping patterns used by emulators.
    * I believe the LUS provided menu should focus on functionality first and foremost. Having the answer to "how do i do x?" be, "you can't" is about as unintuitive as it gets.
    * It might make sense to separate basic/advanced settings as more functionality is added.
  * For port provided menus this is more complex. Ideally a port would follow best practices used by gamepad focused PC games, likely providing a mapping from button to action.
    * LUS may need to provide "extended" controller functionality for this, as ports may want to allow players to use different buttons for menus vs gameplay (for example in SoH, B for sword being mapped to xbox X, B for going back on file select menu being mapped to xbox B)

* "I should be able to get up and running without building my own controller mapping/configuration menu"
  * To provide this, LUS should have a pretty good out of the box menu
  * It might be helpful to provide some basic customization options, such as "how many controller ports should be shown" or "do you need additional axes for right stick/gyro"

### "Out of the box"
* What emulators provide the best controller mapping/configuration UX?
* What controller mapping/configuration features are missing from LUS?
### "Custom"
* What PC games provide the best controller mapping/configuration UX?

**Comment by briaguya0** [comment]
i like how pcsx2 handles it, no selecting a controller from a dropdown, allows mapping from multiple physical devices to one virtual device

![image](https://github.com/Kenix3/libultraship/assets/70942617/dd1cdff5-6d68-41e9-ba1f-7b3928c4ddad)
![image](https://github.com/Kenix3/libultraship/assets/70942617/a4aa5897-8d40-435d-94c5-e02eec695992)
![image](https://github.com/Kenix3/libultraship/assets/70942617/56b6af21-93be-4891-81fa-461afaa7babc)
![image](https://github.com/Kenix3/libultraship/assets/70942617/0cec4439-35c0-4723-8d66-e39aee3d3d36)

it's not clear to me what the sensitivity/deadzone settings on the multiple bindings window do...
![image](https://github.com/Kenix3/libultraship/assets/70942617/4d89df12-b5f0-4662-b268-f05397c91938)

**Comment by briaguya0** [comment]
Batts recommended Half Life 2 (based on how it's handled in orange box on xbox)

edit: turns out this was based on the mappings being good, not the UX for mapping things being good

**Comment by briaguya0** [comment]
came up in https://github.com/HarbourMasters/Shipwright/issues/3215#issuecomment-1725091322 but I'll turn it into a user story here

* As a player with multiple controllers, I want to be able to switch between my controllers without losing my analog deadzone etc. configuration settings.

how this would currently play out
* select controller A from dropdown on port 1
* configure deadzone to be `3`
* select controller B from dropdown on port 1
* configure deadzone to be `6`
* select controller A from dropdown on port 1
* forget that you configured the deadzone to be `3` for that controller, see it's still `6`, painfully go through the process of figuring out what a good deadzone for controller A is again

**Comment by Kenix3** [comment]
> i like how pcsx2 handles it, no selecting a controller from a dropdown, allows mapping from multiple physical devices to one virtual device
> 
> ![image](https://user-images.githubusercontent.com/70942617/268856651-dd1cdff5-6d68-41e9-ba1f-7b3928c4ddad.png) ![image](https://user-images.githubusercontent.com/70942617/268856681-a4aa5897-8d40-435d-94c5-e02eec695992.png) ![image](https://user-images.githubusercontent.com/70942617/268856702-56b6af21-93be-4891-81fa-461afaa7babc.png) ![image](https://user-images.githubusercontent.com/70942617/268856724-0cec4439-35c0-4723-8d66-e39aee3d3d36.png)
> 
> it's not clear to me what the sensitivity/deadzone settings on the multiple bindings window do... ![image](https://user-images.githubusercontent.com/70942617/268859609-4d89df12-b5f0-4662-b268-f05397c91938.png)

LUS supports many to many mapping as long as it's same controller. Supporting controls from multiple controllers into the virtual port would be a large rewrite of the controller code.

**Comment by Kenix3** [comment]
> ## Motivation/User Stories
> 
>     * As a player of a ports using LUS, I should be able to map/configure my controller(s) intuitively.
> 
>     * As a developer of a port using LUS, I should be able to provide a tailored controller mapping/configuration experience for players.
> 
>     * As a developer of a port using LUS, I should be able to get up and running without building my own controller mapping/configuration menu.
> 
> 
> ## Definitions
> 
>     * "I should be able to map/configure my controller(s) intuitively."
>       
>       * For the LUS provided menu, following best practices used by emulators makes sense. Mapping from button/axis on a physical device to N64 button/axis using language related to N64 buttons/axes provides all the functionality a port will need to get up and running. "Intuitive," in this case, means "intuitive to people familiar with the original game controls on N64 and familiar with controller mapping patterns used by emulators.
>         
>         * I believe the LUS provided menu should focus on functionality first and foremost. Having the answer to "how do i do x?" be, "you can't" is about as unintuitive as it gets.
>         * It might make sense to separate basic/advanced settings as more functionality is added.
>       * For port provided menus this is more complex. Ideally a port would follow best practices used by gamepad focused PC games, likely providing a mapping from button to action.
>         
>         * LUS may need to provide "extended" controller functionality for this, as ports may want to allow players to use different buttons for menus vs gameplay (for example in SoH, B for sword being mapped to xbox X, B for going back on file select menu being mapped to xbox B)
> 
>     * "I should be able to get up and running without building my own controller mapping/configuration menu"
>       
>       * To provide this, LUS should have a pretty good out of the box menu
>       * It might be helpful to provide some basic customization options, such as "how many controller ports should be shown" or "do you need additional axes for right stick/gyro"
> 
> 
> ## Discovery
> ### "Out of the box"
> 
>     * What emulators provide the best controller mapping/configuration UX?
> 
>     * What controller mapping/configuration features are missing from LUS?
> 
> 
> ### "Custom"
> 
>     * What PC games provide the best controller mapping/configuration UX?

Can you give specific examples about what is not intuitive?

**Comment by Kenix3** [comment]
> came up in [HarbourMasters/Shipwright#3215 (comment)](https://github.com/HarbourMasters/Shipwright/issues/3215#issuecomment-1725091322) but I'll turn it into a user story here
> 
>     * As a player with multiple controllers, I want to be able to switch between my controllers without losing my analog deadzone etc. configuration settings.
> 
> 
> how this would currently play out
> 
>     * select controller A from dropdown on port 1
> 
>     * configure deadzone to be `3`
> 
>     * select controller B from dropdown on port 1
> 
>     * configure deadzone to be `6`
> 
>     * select controller A from dropdown on port 1
> 
>     * forget that you configured the deadzone to be `3` for that controller, see it's still `6`, painfully go through the process of figuring out what a good deadzone for controller A is again

What has convinced you that players see the deadzone relative to their physical controller? Either way, what other data do you envision that users see at the physical level?

Further, how does all of this map to how we save data today? What changes would we need to make?

**Comment by briaguya0** [comment]
> ## Can you give specific examples about what is not intuitive?

* "Auto"
  * There is no documentation around how this is intended to work. it seems to allow input from multiple controllers sometimes but not always? 
* it's not clear what mappings are associated with
  * map xbox controller, save (toggle menubar), disconnect xbox controller, connect ps5 controller, mapping works on ps5 controller (maybe that's a good thing?)
  * map xbox controller, save (toggle menubar), connect ps5 controller, connect xbox controller, select xbox controller from dropdown, it has the default mapping? (this feels like a bad thing)
* saving requires toggling menubar
  * we should either autosave or have a "save" button
* hitting refresh next to the dropdown clears "unsaved" mappings
  * it should be clear when a mapping is saved and when we have unsaved changes, if refreshing to see new controllers in the dropdown clears unsaved changes we should at least warn users

> ## What has convinced you that players see the deadzone relative to their physical controller? 

what would be the point of a deadzone otherwise? a player wants to ensure when the move the stick it works as they expect it to. different physical controllers have different sticks with different deadzone needs.

it also seems like we already coded that assumption in
https://github.com/Kenix3/libultraship/blob/1c580200635339d0d9c0722c601303369b39d467/src/controller/Controller.h#L24-L35

after doing a bit of testing, i'm thinking this is part of a bigger problem i noted earlier in here under "it's not clear what mappings are associated with"

i'm thinking this might be related to our heavy reliance on accessing devices within `std::vector<std::shared_ptr<Controller>> mDevices;` based on index instead of some kind of unique identifier. `Controller` does have `mGuid` available, but that is only model specific

that being said, it still might make sense to save that guid into the `DeviceProfile` or something. That would at least get us to a point where we would be able to have logic to not apply a profile from an xbox controller to a ps5 controller.

doing that would take away the "feature" of "map xbox controller, save (toggle menubar), disconnect xbox controller, connect ps5 controller, mapping works on ps5 controller,"

## overall thoughts

I think most of the UX issues with the controller mapping menu stem from the behavior of the controller select dropdown. PCSX2 gets around this by not having one. Dolphin has a dropdown, but selecting a controller from it doesn't change anything in the mappings. Both of these solutions address what feels like the biggest UX failure we have, which is "losing" controller mapping data and not knowing why.

Another feature of both Dolphin and PCSX2 that is incredibly helpful is the ability to save and load profiles. This works around the unique identifier issue by allowing users to save a configuration and then apply it to any controller they would like. I haven't done a lot of investigation as to how these work in PCSX2 as the mapping includes the SDL device index (can you apply a profile with SDL buttons from SDL0 to SDL1?), but in dolphin it's pretty straightforward.

## recommendations

### Option A: follow the dolphin pattern
If we do this it will be incredibly easy to create a mapping on one device, and then switch to a different one in the dropdown without losing any settings. From a UX perspective I think we should move away from hiding elements that don't apply to a selected controller (analog for keyboard/gyro for non-gyro controllers) and maybe just disable them (we might still want a way to clear these when they're disabled). This would ensure players could still see any existing mappings regardless of the selected device.

### Option B: follow the PCSX2 pattern
I like this one more because it means we can ditch the dropdown. It would require a bit more of a rework but the idea of a player being able to just hop into the config menu, click on a map button, press a button on any connected controller, and have stuff just work seems pretty awesome to me. Implementing "automatic mapping" like PCSX2 has seems like a really great way to handle all of this.

**Comment by briaguya0** [comment]
i sent this on discord but i figure it makes sense to have here so it doesn't get lost in a channel

> i responded to that and your other questions with a pretty long comment with a few examples and some other notes, but i don't think i fully answered in the way i was hoping to.

> the point of the UX discovery issue is to find good examples of intuitive controller mapping UX, learn from them, and see how we could implement them into the controller mapping menu in LUS. i see the path forward as:

> 1. discovery: what good controller mapping ux patterns are out there?
> 2. definition: what does good controller mapping ux look like in the context of LUS?
> 3. discovery: in what ways are we falling short of our definition of good controller mapping UX?
> 4. definition: what can we do to address those shortcomings and bring our implementation closer in line with our definition of good controller mapping UX?


> i feel like my answer to your question was kind of rambly because you were asking 3, which i see as requiring the context of 2 (which hasn't happened because we're not done with 1)

**Comment by briaguya0** [comment]
this was a discovery issue and the findings were implemented in the rework
