### ISSUE TITLE
refactor away from giant f3d switch/case ifdef stuff

### ISSUE THREAD

**Issue by briaguya0** [Kenix3/libultraship#405]
* A minimalist approach would be to copy gfx_pc run_dl function, remove the ifdefs, and have a different version of this function per supported GBI.
* This is basically refactoring Fast3D to not rely on GBI.
* Fast3D needs to be told what GBI version we are rendering with.
* Fast3D will need handler functions for each GBI opcode, for each different GBI supported.
* Design is very inspired by gliden64.
* It would be nice if Fast3D were a class.
* ideally support choosing GBI at runtime instead of compile time

https://github.com/Kenix3/libultraship/blob/0aa972b6e761273d2c97aa01ed0fd0dfb3888e6a/src/graphic/Fast3D/gfx_pc.cpp#L2484

https://github.com/Kenix3/libultraship/blob/0aa972b6e761273d2c97aa01ed0fd0dfb3888e6a/src/graphic/Fast3D/gfx_pc.cpp#L2527-L2531

**Comment by Kenix3** [comment]
Resolved here: https://github.com/Kenix3/libultraship/pull/461
