### ISSUE TITLE
2.0 discussion

### ISSUE THREAD

**Issue by briaguya0** [Kenix3/libultraship#407]
# O2R

## required
-   finish otr support in new architectures (easy)
    -   There's an ArchiveManager instead of just an Archive class. Implement the subclass OTR of the class Archive.
    -   There's already existing code to work with OTRs which can be moved into the new class

-   todos in resource manager (before o2rs are pushed)
    -   Kenix's local code has some todos.

-   o2r support (nearly done)
    -   Need to get in the zip library into LUS' cmake build system
    -   Implement functions in O2rArchive class
        -   HasFile
        -   LoadFile
        -   LoadFileRaw
        -   LoadArchive
        -   UnloadArchive

-   Ensure the Archive list can be cleared and reloaded with new Archives.
    -   Add a function for clearing all archives in ArchiveManager
    -   AddArchive function in ArchiveManager should be public
    
-   Build option to build without StormLib and otr support. This default would only use o2r.

## optional

-   Benchmark OTR vs O2R
-   Archive subclass to read from disk (not necessary for 2.0, but we lost this in the new archive architecture
    -   High priority - can be 2.1

# GBI Differences

-   A minimalist approach would be to copy gfx_pc run_dl function, remove the ifdefs, and have a different version of this function per supported GBI.
-   This is basically refactoring Fast3D to not rely on GBI.
-   Fast3D needs to be told what GBI version we are rendering with.
-   Fast3D will need handler functions for each GBI opcode, for each different GBI supported.
-   Design is very inspired by gliden64.
-   It would be nice if Fast3D were a class.
-   https://github.com/Kenix3/libultraship/issues/405

# exporters in factories 

-   Existing exporters in LUS are just going away.
-   Importers in LUS will not have an importer for importing FROM binary and FROM xml. This should be arbitrary as well.
-   Basically the entire ResourceFactory class is going to be redone.
    -   Blocked on initial o2r
    -   From any to any
    -   no ReadResource vs ReadResourceXML
    -   ReadResource should take a File (the resource factories will need to be changed)
    -   Export/extract returns a binary blob
    -   Look into better names for ResourceFactory and ResourceVersionFactory
    -   Can we change ResourceFactory such that it works for all Resources, and we don't need a ResourceFactory for each resource type.

-   Kenix is OK with other people creating an export system, as long as it can export to "any" format. These would be either implemented in all LUS Factories, OR would be stubs in the base class that are virtual so they can be overridden.

# Other

## required

-   [Cherry pick the PD changes for LUS](https://github.com/Kenix3/libultraship/issues/404) in (https://github.com/HarbourMasters/libultraship/commits/main)
    -   There's a few function implementations we want. There isn't a lot here, though, and most of it is copy/pastable. The caveat here is that we don't want all of the changes.
-    [Cherry pick SM64 changes for LUS](https://github.com/Kenix3/libultraship/pull/373)
    -   There's a few function implementations we want. There isn't a lot here, though, and most of it is copy/pastable. The caveat here is that we don't want all of the changes.
- Remove ZAPDUtils deps

# Libultra headers

-   Punt on providing a reimplementation for all libultra functions to post-2.0
-   LUS will no longer have libultra headers. It is expected the ported game will provide them.
    -   In case of conflict (different versions of the same function in different ports), split out LUS version of function into versions, use #ifdefs
    -   A goal of LUS is to provide a linker compatible function for games.

# sdk/lus split
-   Should be completed last.
-   Basically we split the libultra compatible functions from the existing LUS helper classes. The LUS helper classes will become sdk. The libultra compatible functions will stay as LUS. The renderer stays in LUS. sdk is basically the "back end" for how LUS handles stuff.
-   Follow the same pattern as splitting LUS out of SoH, wait til post 2.0

# non-core platform decisions (split out wii u and switch?)

-   We split
-   Fork at LUS 2.0 RC#
    -   LUS 2.0 removes ifdefs
    -   LUS 2.0 - Switch removes ifdefs
    -   LUS 2.0 - Wii U removes ifdefs

-   Fork SoH
    -   SoH uses LUS 2.0 - removes switch/wii u
    -   SoH Switch uses LUS 2.0 Switch
    -   SoH Wii U uses LUS 2.0 Wii U

# controllers

## required

-   oscontpad lus only, not shipdk

## optional

-   rumble in LUS? (osMotor\* funcs)
-   (probably post 2.0) controller pak support
-  (probably post 2.0) (would like to wait for sdl3) https://github.com/Kenix3/libultraship/issues/411

# ABI Differences

-   Punt on ABI for post-2.0
-   Basically we want something like Fast3D, but for audio ucode. We can use the mixer.c in SoH, PD, and SM64 as examples for how to deal with differences.

**Comment by PeeMoldy** [comment]
What is this in a nutshell?

**Comment by Kenix3** [comment]
Will capture the necessary tasks elsewhere.
