### ISSUE TITLE
They blocked me from the HarbourMasters Shipwright!

### ISSUE THREAD

**Issue by PeeMoldy** [Kenix3/libultraship#412]
https://github.com/HarbourMasters/code-of-conduct

I didn't break any code of conduct, yet I was blocked on HarbourMasters Shipwright. I don't know why or who did this. Also sorry if this is not the right place for this, but this is the only way I know how to contact the Repository Owner.

**Comment by sheepytina** [comment]
Bringing personal drama into a different project's GitHub definitely seems like it would break GitHub's [community guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines) though. This is spam, and a waste of everyone's time. Quit it.

**Comment by PeeMoldy** [comment]
> Bringing personal drama into a different project's GitHub definitely seems like it would break GitHub's [community guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines) though. This is spam, and a waste of everyone's time. Quit it.

So it was you... Why you block me? I just don't know how to contact the repository owner. I have no personal drama. Do you?

**Comment by sheepytina** [comment]
> So it was you... Why you block me? I just don't know how to contact the repository owner. I have no personal drama. Do you?

That's a completely baseless claim. It couldn't have been me because I'm not a maintainer of that project, nor this one. I'm just calling you out on your immature behavior. 

"Personal drama" means complaining about being banned and bringing that discussion into an unrelated place. GitHub issues are specifically for talking about the project in question, which this is not. You were likely blocked for continuing making useless comments _after you were warned multiple times_ by the maintainers on the Shipwright repo. You were asked to stop and willfully ignored it. Don't pretend that you don't know what happened, because you clearly do.

lilbultraship is not Ship of Harkinian and is used by more than just SoH. Not all of the maintainers of Ship of Harkinian are even involved in libultraship either, so you're wasting your breath by bringing this here.

**Comment by PeeMoldy** [comment]
> > So it was you... Why you block me? I just don't know how to contact the repository owner. I have no personal drama. Do you?
> 
> That's a completely baseless claim. It couldn't have been me because I'm not a maintainer of that project, nor this one. I'm just calling you out on your immature behavior.
> 
> "Personal drama" means complaining about being banned and bringing that discussion into an unrelated place. GitHub issues are specifically for talking about the project in question, which this is not. You were likely blocked for continuing making useless comments _after you were warned multiple times_ by the maintainers on the Shipwright repo. You were asked to stop and willfully ignored it. Don't pretend that you don't know what happened, because you clearly do.
> 
> lilbultraship is not Ship of Harkinian and is used by more than just SoH. Not all of the maintainers of Ship of Harkinian are even involved in libultraship either, so you're wasting your breath by bringing this here.

Hey I don't like your attitude Mr. You can calm it down and talk like an adult to me. I think you conspired against me because of my religious beliefs. Are you a part of the group "Antifa" or something? You had me blocked because you don't like that I believe men cannot be women. That's why you thumbing down my posts. I see you Antifa. Very dirty of you to discriminate against me like this.

**Comment by PeeMoldy** [comment]
> > So it was you... Why you block me? I just don't know how to contact the repository owner. I have no personal drama. Do you?
> 
> That's a completely baseless claim. It couldn't have been me because I'm not a maintainer of that project, nor this one. I'm just calling you out on your immature behavior.
> 
> "Personal drama" means complaining about being banned and bringing that discussion into an unrelated place. GitHub issues are specifically for talking about the project in question, which this is not. You were likely blocked for continuing making useless comments _after you were warned multiple times_ by the maintainers on the Shipwright repo. You were asked to stop and willfully ignored it. Don't pretend that you don't know what happened, because you clearly do.
> 
> lilbultraship is not Ship of Harkinian and is used by more than just SoH. Not all of the maintainers of Ship of Harkinian are even involved in libultraship either, so you're wasting your breath by bringing this here.

Reported for religious discrimination and blocked. We know what this is all about, what a shame.

**Comment by PeeMoldy** [comment]
I'm going to close this out of respect for repository owner. It's a shame sheepytina/Rex and his crew hate me because of my religion, this is why he thumbed down my comments. Conspiracies against people because of their religion is a shame.

**Comment by aMannus** [comment]
@PeeMoldy you've been told numerous times to stop the irrelevant discussion on pull requests and you didn't listen, that's why you were banned from the repo. Seeing this issue, I'm confident that was the right call.

**Comment by PeeMoldy** [comment]
> @PeeMoldy you've been told numerous times to stop the irrelevant discussion on pull requests and you didn't listen, that's why you were banned from the repo. Seeing this issue, I'm confident that was the right call.

I didn't even post in like 2 days. Are you an Antifa conspiring against me with SheepyRex because of my religions beliefs in Deuteronomy 22:5? I think you are, you now admit you are part of the conspiracy against me because of my religion, it is shameful. You wouldn't "warn" a fellow atheist like this.

**Comment by PeeMoldy** [comment]
> @PeeMoldy you've been told numerous times to stop the irrelevant discussion on pull requests and you didn't listen, that's why you were banned from the repo. Seeing this issue, I'm confident that was the right call.

Blocked and reported for religious discrimination. It's outright pathetic that this person thinks conspiring against people because of their religious believes and their "woke" political agenda is OK. Very sad day on Github. I hope that one day this horrible religious discrimination against me and others can stop.

**Comment by PurpleHato** [comment]
Your behavior is absurd. Attacking people with false claims and sheer stupidity is unacceptable and we'll not talk about your intolerance.
Consider yourself fortunate that I lack administrative rights over this repo; otherwise, your intolerant conduct would have been swiftly addressed from the start.

Compassion is hard to muster at this point. Your refusal to stop this detrimental behavior despite warnings is a disheartening display of a sick mindset. It's time to reflect on the consequences of your actions and intolerance before contributing further to this unhealthy atmosphere.

Best of luck in your future endeavors; it seems you might require it.

**Comment by PeeMoldy** [comment]
> Your behavior is absurd. Attacking people with false claims and sheer stupidity is unacceptable and we'll not talk about your intolerance. Consider yourself fortunate that I lack administrative rights over this repo; otherwise, your intolerant conduct would have been swiftly addressed from the start.
> 
> Compassion is hard to muster at this point. Your refusal to stop this detrimental behavior despite warnings is a disheartening display of a sick mindset. It's time to reflect on the consequences of your actions and intolerance before contributing further to this unhealthy atmosphere.
> 
> Best of luck in your future endeavors; it seems you might require it.

Why do you think discrimination against my religious beliefs is "OK and tolerant"? Are you also a member of "Antifa"?

**Comment by PeeMoldy** [comment]
> Your behavior is absurd. Attacking people with false claims and sheer stupidity is unacceptable and we'll not talk about your intolerance. Consider yourself fortunate that I lack administrative rights over this repo; otherwise, your intolerant conduct would have been swiftly addressed from the start.
> 
> Compassion is hard to muster at this point. Your refusal to stop this detrimental behavior despite warnings is a disheartening display of a sick mindset. It's time to reflect on the consequences of your actions and intolerance before contributing further to this unhealthy atmosphere.
> 
> Best of luck in your future endeavors; it seems you might require it.

Reported and blocked as part of the "sheepytina"/aMannus Antifa conspiracy against me due to my religious beliefs, uses personal attacks and vile language against me.

**Comment by KiritoDv** [comment]
@PeeMoldy I dont know how you didnt see that no one cares a damn about your religion, you are getting blocked because you seem to be incapable of following instructions or even the rules, so please stop wasting your and our time since you are filling every repo you can with stupid questions.

**Comment by PeeMoldy** [comment]
It's a shame that at least 3 people, "Sheepytina", "aMannus", and "PurpleHato" do not like me for religious reasons and would abuse their power to ban me and try to silence me because of their Far Left Marxist political agenda. Games are for everyone, and that includes Christians and those who do not support the evil of Karl Marx. I didn't even post for like 2 days, and then I get banned because its open season on anyone who loves Lord Jesus and rejects Cultural Marxism, but I will speak on it and make it known. I will not allow evil to prevail. I really wish these people learned to love games more than they hate others for being different from them.

**Comment by PeeMoldy** [comment]
> @PeeMoldy I dont know how you didnt see that no one cares a damn about your religion, you are getting blocked because you seem to be incapable of following instructions or even the rules, so please stop wasting your and our time since you are filling every repo you can with stupid questions.

I just think it sucks that you would discriminate against me because of my religion, and then turn around and lie about it. Why do you think conspiring against people is OK?

**Comment by PeeMoldy** [comment]
> @PeeMoldy I dont know how you didnt see that no one cares a damn about your religion, you are getting blocked because you seem to be incapable of following instructions or even the rules, so please stop wasting your and our time since you are filling every repo you can with stupid questions.

Reported and blocked for being part of the "sheepytina", aMannus, and PurpleHato conspiracy against me due to my religious beliefs, this is a sad day. Why can't we end discrimination against people today?

**Comment by PeeMoldy** [comment]
> @PeeMoldy I dont know how you didnt see that no one cares a damn about your religion, you are getting blocked because you seem to be incapable of following instructions or even the rules, so please stop wasting your and our time since you are filling every repo you can with stupid questions.

I asked you about OGGs man? What's stupid about that? Or is it because you hate me due to me having a different religion than you? So you want to get with corrupt aMannus and sheepytina and PurpleHato and get rid of those who do not agree with your Cultural Marxist POV. To silence them. Cancel Culture, yeah I'm hip to your schemes.

**Comment by PeeMoldy** [comment]
> @PeeMoldy you've been told numerous times to stop the irrelevant discussion on pull requests and you didn't listen, that's why you were banned from the repo. Seeing this issue, I'm confident that was the right call.

https://github.com/HarbourMasters/Shipwright/pull/3796

Completely on topic here, yet this Antifa discriminator aMannus marked my replies as off topic. The topic is the draw bridge right? And part of the draw bridge are the rupees that you can get on the top, right? So that's ON TOPIC. But you don't like it when a non-leftist or non-atheist asks questions, because you consider yourself superior to everyone who disagree with your Far-Left Marxist politics, so you abuse your "powers" that you think you have. We saw this happening on Twitter all the time before Elon brought it out. Shame on you!

**Comment by PeeMoldy** [comment]
I will say this, because I know I will be silenced and harassed, but I'm going to say it here now, loud, proud, and knowing that Jesus Christ is my Lord and Savior. I love Ship of Harkinian and libultraship, I think it's revolutionary, but I wish that some people who were part of both projects didn't have discriminatory, hateful, Anti-Christian, Pro-Leftist, Marxist, Antifa mindsets where they feel they got to dehumanize those who love Jesus and reject the pure evil of the Left Wing Antifa Marxists, who are known to be violent. I think this project would be so much better if some of those people like "sheepytina", aMannus, PurpleHato, and KiritoDv, and any other conspirator against me and other Christians who haven't come forward yet, did not try to discriminate against, conspire against, or ban non-Atheist/non-Leftist/non-Antifa contributors and those who innocently ask questions, or may not understand EVERYTHING about OoT, or SoH, or C, C++, Python, Assembly Code, etc. Stop thinking you are better than everyone, and that people's questions on complex issues like code and games are illegitimate, just because you hate those different than you, or hate those who believe in 2 genders and not 72 genders. I hope this pure evil "woke" mentality disappears from this world forever, because it's holding everyone and everything back. It's outright destructive and insane. I hope some brave people join me in calling out those evil conspirators, and call for them to be banned, temporarily, maybe they can learn not to be so hateful, then come back and contribute without your hatred and false thoughts of superiority over others who are not like you, or might not know how a certain aspect of coding works.

**Comment by PeeMoldy** [comment]
I was just wrongfully suspended, but now that was reversed. I am going to get PurpleHato and KiritoDv suspended for their personal attacks. Support already knows about this.

**Comment by PeeMoldy** [comment]
> @PeeMoldy I dont know how you didnt see that no one cares a damn about your religion, you are getting blocked because you seem to be incapable of following instructions or even the rules, so please stop wasting your and our time since you are filling every repo you can with stupid questions.

Hey support, you see this? This is a personal attack against me!

**Comment by PeeMoldy** [comment]
> Your behavior is absurd. Attacking people with false claims and sheer stupidity is unacceptable and we'll not talk about your intolerance. Consider yourself fortunate that I lack administrative rights over this repo; otherwise, your intolerant conduct would have been swiftly addressed from the start.
> 
> Compassion is hard to muster at this point. Your refusal to stop this detrimental behavior despite warnings is a disheartening display of a sick mindset. It's time to reflect on the consequences of your actions and intolerance before contributing further to this unhealthy atmosphere.
> 
> Best of luck in your future endeavors; it seems you might require it.

Hey support, see this personal attack and threat against me?

**Comment by PeeMoldy** [comment]
https://github.com/aMannus/HolidaysInHyrule/issues/12

You gotta love how I brought up legit issues, and aMannus banned me because he is discriminating against me along with his minions "Sheepytina", and personal attacker KiritoDv, and personal attacker/threatener PurpleHato.
