### ISSUE TITLE
Remove ZAPDUtils as a dependency on LUS.

### ISSUE THREAD

**Issue by Kenix3** [Kenix3/libultraship#484]
Anything LUS still needs can be copied over.

**Comment by briaguya0** [comment]
all zapdutils stuff we're using lives in https://github.com/Kenix3/libultraship/tree/main/extern/ZAPDUtils, note ZAPDUtils as deprecated so any consumers of LUS know not to use it (so we can move/absorb functionality)

**Comment by briaguya0** [comment]
remove zapdutils from LUS
add just what we need from it to get LUS building
get the rest of everything that needs zapdutils to pull it from somewhere else
