### ISSUE TITLE
move switch/wii u to forks, remove switch/wii u specific code

### ISSUE THREAD

**Issue by briaguya0** [Kenix3/libultraship#485]
* get to a point where we're ready to tag 2.0 
* fork off switch and wii u versions that have all that code still intact
* rip out the switch/wii u stuff from the main repo and tag 2.0

**Comment by m4xw** [comment]
Switch is first class citizen maintained by Lywx and technically still me.
A bunch of defines hardly warrants splitting it off in a fork https://github.com/search?q=repo%3AKenix3%2Flibultraship%20__switch__&type=code

Given the higher maintenance work for Wiiu's custom renderer (and even the old Vita port) I guess that would be up to Gary to decide.
