### ISSUE TITLE
Confirm that all commits on the `1.x` branch after the split from `2.x` are replicated in the main branch

### ISSUE THREAD

**Issue by Kenix3** [Kenix3/libultraship#517]
This is also blocked by MacReady Golf release on SoH.

**Comment by briaguya0** [comment]
- [x] https://github.com/Kenix3/libultraship/pull/372 (https://github.com/Kenix3/libultraship/pull/379)
- [x] https://github.com/Kenix3/libultraship/pull/377 (https://github.com/Kenix3/libultraship/pull/380)
- [x] https://github.com/Kenix3/libultraship/pull/384 (https://github.com/Kenix3/libultraship/pull/387)
- [x] https://github.com/Kenix3/libultraship/pull/388 (https://github.com/Kenix3/libultraship/pull/389)
- [x] https://github.com/Kenix3/libultraship/commit/59427a67bf9af060a4928bb72e3acce3b0782177 (https://github.com/Kenix3/libultraship/pull/364)
- [x] https://github.com/Kenix3/libultraship/pull/393 (https://github.com/Kenix3/libultraship/pull/395)
- [x] https://github.com/Kenix3/libultraship/pull/397 (https://github.com/Kenix3/libultraship/pull/398)
- [x] https://github.com/Kenix3/libultraship/pull/396
- [x] https://github.com/Kenix3/libultraship/pull/394
- [x] https://github.com/Kenix3/libultraship/pull/408 (https://github.com/Kenix3/libultraship/pull/409)
- [x] https://github.com/Kenix3/libultraship/pull/538
