### ISSUE TITLE
Newer StormLib significantly slower loading OTR files

### ISSUE THREAD

**Issue by Malkierian** [Kenix3/libultraship#568]
With the changes happening with all the dependencies, StormLib was updated at the same time as being moved to external dependency management, from 9.00 to 9.25. This has introduced a massive increase in load time surrounding the OTRs on boot. Before this change, this would be a typical startup:

https://github.com/Kenix3/libultraship/assets/774771/15fa6718-4ec9-46b2-8869-5f559e9b5480

It took about 33% longer because my computer sucks and recording was happening. Usually it would be about 5-7 seconds to the splash screen. After the change, this becomes the standard experience:

https://github.com/Kenix3/libultraship/assets/774771/c0a20fae-36f5-49ce-b4c5-52b034799b1c

Again, about 33% longer because of recording, but normally without the recording it would be 30-35 seconds to the splash screen. I wouldn't be surprised if this also affected mod asset loading times, but this laptop is not the machine to profile that.

**Comment by Malkierian** [comment]
Forgot to mention, I configure with CMake in release mode all the time, and running from VS in release mode made no noticeable difference.

**Comment by Kenix3** [comment]
Resolved in https://github.com/Kenix3/libultraship/pull/571
