### ISSUE TITLE
Do not require Context to use Fast3dWindow.

### ISSUE THREAD

**Issue by Kenix3** [Kenix3/libultraship#577]
How are we going to accomplish this since the Window is an abstract base class?
Basically the idea is to pass a Window in for the Context constructor, and the createInstance method.

**Comment by briaguya0** [comment]
https://github.com/Kenix3/libultraship/blob/00c6bcc88286173ce22b8a6656373d3aa5830c62/src/Context.cpp#L258-L265

ports should do this and pass it into context instead of `guiWindows`
