### ISSUE TITLE
Only auto-configure one controller device automatically

### ISSUE THREAD

**Issue by garrettjoecox** [Kenix3/libultraship#595]
The new controller mapping UI is a huge improvement over the old one, however that is completely shadowed by the fact that on startup we auto map all connected controllers, so what the end user ends up seeing is this;

<img width="684" alt="Screenshot 2024-05-20 at 2 31 50 PM" src="https://github.com/Kenix3/libultraship/assets/7316699/a916086a-4aef-4f41-bf73-fdf6d16ee298">

Which is so immensely overwhelming, the users first reaction is to clear all bindings, rendering the "auto configure" useless in the first place.

IMO We should just auto map one connected device, and if we guessed the wrong device, then the user should go in and identify the controller they want to map, but this is subjective, open to other ideas.

**Comment by Archez** [comment]
Additionally, the `Set Defaults` option does not allow for setting keyboard defaults. So if you use `Clear All`, you can't ever get the keyboard binds back without manually setting them all.

(maybe this should be a separate issue)

**Comment by briaguya0** [comment]
i think there are a couple ways to address this:
* what you suggested about only mapping 1
  * i can look into using `ControllerReorderingWindow` to handle this so we prompt the player to press a button on a controller to know which one
* add an ability to filter mappings
  * hide disconnected device mappings
  * show only mappings for a selected device

the idea behind "single player mode" (which is what is being shown here), is that no matter what controller you pick up it'll "just work" to start playing - as opposed to multiplayer mode where it prompts to know which controller should go to which "controller port"

**Comment by briaguya0** [comment]
> Additionally, the `Set Defaults` option does not allow for setting keyboard defaults. So if you use `Clear All`, you can't ever get the keyboard binds back without manually setting them all.
> 
> (maybe this should be a separate issue)

yeah, this feels like a separate issue

**Comment by briaguya0** [comment]
i guess i really didn't expect people to have 5 controllers connected to their computers at all times

**Comment by garrettjoecox** [comment]
> i guess i really didn't expect people to have 5 controllers connected to their computers at all times

I think in the case of retro enthusiasts, what's usually going on is they will have a generic bluetooh controller connected for when they want to use that with modern games, then they have a single retro controller (gc/n64) connected through an adatper, and adapters auto register as 4 controllers, resulting in the 5

**Comment by briaguya0** [comment]
resolved by https://github.com/HarbourMasters/Shipwright/pull/4165 making it into LUS via https://github.com/Kenix3/libultraship/pull/630

note: all controllers are still auto-configured, this just adds a way to toggle visibility (and defaults to only showing keyboard and the first controller)
