### ISSUE TITLE
Allow setting keyboard defaults in the new input editor

### ISSUE THREAD

**Issue by Archez** [Kenix3/libultraship#596]
The `Set Defaults` option does not allow for setting keyboard defaults. So if you use `Clear All`, you can't ever get the keyboard binds back without manually setting them all.

**Comment by briaguya0** [comment]
![image](https://github.com/Kenix3/libultraship/assets/70942617/e8f13c5d-0519-48cd-aa26-0522d3c2a367)

setting keyboard defaults works in soh, must be something that i added/fixed there that hasn't made it into the LUS input editor window yet

probably worth going through the soh input editor window changes and seeing what's not SoH specific and worth bringing over to the LUS side

**Comment by briaguya0** [comment]
resolved by https://github.com/Kenix3/libultraship/pull/630
