### ISSUE TITLE
Drop explicit void when no parameters

### ISSUE THREAD

**Issue by Kenix3** [Kenix3/libultraship#698]

**Comment by briaguya0** [comment]
https://github.com/Kenix3/libultraship/blob/00c6bcc88286173ce22b8a6656373d3aa5830c62/src/audio/AudioPlayer.h#L21-L22

https://github.com/Kenix3/libultraship/blob/00c6bcc88286173ce22b8a6656373d3aa5830c62/src/audio/AudioPlayer.h#L25

https://github.com/Kenix3/libultraship/blob/00c6bcc88286173ce22b8a6656373d3aa5830c62/src/audio/AudioPlayer.h#L52

**Comment by briaguya0** [comment]
https://github.com/Kenix3/libultraship/blob/00c6bcc88286173ce22b8a6656373d3aa5830c62/src/audio/SDLAudioPlayer.h#L12

https://github.com/Kenix3/libultraship/blob/00c6bcc88286173ce22b8a6656373d3aa5830c62/src/audio/SDLAudioPlayer.h#L16

**Comment by briaguya0** [comment]
https://github.com/Kenix3/libultraship/blob/00c6bcc88286173ce22b8a6656373d3aa5830c62/src/audio/WasapiAudioPlayer.h#L18

https://github.com/Kenix3/libultraship/blob/00c6bcc88286173ce22b8a6656373d3aa5830c62/src/audio/WasapiAudioPlayer.h#L31-L32
