### ISSUE TITLE
make `DidLoadSuccessfully` protected instead of public

### ISSUE THREAD

**Issue by briaguya0** [Kenix3/libultraship#710]
https://github.com/Kenix3/libultraship/blob/00c6bcc88286173ce22b8a6656373d3aa5830c62/src/resource/ResourceManager.h#L54

is only ever used in `ResourceManager` itself, i'd say make it private but protected gives us some wiggle room

**Comment by Kenix3** [comment]
Used in bridge, so it can not be protected.
